# Generated by Django 3.0.4 on 2020-09-16 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200916_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 17, 7, 30, 418845, tzinfo=utc), verbose_name='Data da criação'),
        ),
    ]
