# Generated by Django 3.0.4 on 2020-09-18 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação'),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da criação'),
        ),
    ]
