# Generated by Django 3.0.4 on 2020-09-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200918_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='pub_date',
        ),
    ]
